#!/usr/bin/env bash

# shellcheck disable=SC2236
if [ ! -z "$WWWUSER" ]; then
    usermod -u "$WWWUSER" sail
fi

if [ "$APP_ENV" == "production" ]; then
    php artisan clear-compiled -n --ansi
    php artisan optimize -n --ansi
    php artisan config:cache -n --ansi
    php artisan route:cache -n --ansi
    php artisan view:cache -n --ansi
    php artisan event:cache -n --ansi
    php artisan permission:cache-reset -n --ansi
    php artisan filament:cache-components -n --ansi
    php artisan schedule-monitor:sync -n --ansi
    php artisan about
fi

if [ $# -gt 0 ]; then
    exec gosu "$WWWUSER" "$@"
else
    exec /usr/bin/supervisord -c /etc/supervisor/supervisord.conf
fi
