#!/usr/bin/env bash

# shellcheck disable=SC2236
if [ ! -z "$WWWUSER" ]; then
    usermod -u "$WWWUSER" sail
fi

if [ "$APP_ENV" == "production" ]; then
    php artisan clear-compiled -n
    php artisan optimize -n
    php artisan route:cache -n
    php artisan view:cache -n
    php artisan event:cache -n
    php artisan permission:cache-reset -n
fi

if [ $# -gt 0 ]; then
    exec gosu "$WWWUSER" "$@"
else
    exec /usr/bin/supervisord -c /etc/supervisor/supervisord.conf
fi
