#!/usr/bin/env bash

docker build \
    --build-arg WWWUSER="$(id -u)" \
    --build-arg WWWUSER="$(id -g)" \
    --build-arg BASE="ghcr.io/codelieutenant/website:base" \
    --file ./docker/php/Dockerfile \
    --target production \
    --tag ghcr.io/codelieutenant/website:latest \
    .
