#!/bin/sh

docker run -it -d \
  --network dusan_malusev \
  --privileged \
  --env-file ./.env \
  -p 80:80 \
  -p 2019:2019 \
  ghcr.io/codelieutenant/website:latest \
    /bin/start-container php artisan octane:start \
      --host=0.0.0.0 \
      --port=80 \
      --admin-port=2019 \
      -vvv