#!/usr/bin/env bash

php artisan clear-compiled -n --ansi
php artisan optimize -n --ansi
php artisan config:cache -n --ansi
php artisan route:cache -n --ansi
php artisan view:cache -n --ansi
php artisan event:cache -n --ansi
php artisan permission:cache-reset -n --ansi
php artisan filament:cache-components -n --ansi
php artisan schedule-monitor:sync -n --ansi
php artisan icons:cache -n --ansi
php artisan permissions:sync -n --ansi
php artisan about

exec $@